version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: projectdatabase
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
        - 5432:5432
    logging:
        driver: none
    environment:
       - POSTGRES_PASSWORD=DBPassword