@ReactApp.Server_HostAddress = http://localhost:5030

GET {{ReactApp.Server_HostAddress}}/user/
Accept: application/json

###

GET {{ReactApp.Server_HostAddress}}/user/{id}
Accept: application/json

###

PUT {{ReactApp.Server_HostAddress}}/user/{id}
Accept: application/json

###

GET {{ReactApp.Server_HostAddress}}/projectrole/
Accept: application/json

###

GET {{ReactApp.Server_HostAddress}}/project/
Accept: application/json